const data = {
  products: [
    {
      _id: "1",
      name: "Mate 10 Lite",
      category: "Szkła hartowane",
      image: "/images/Mate10Lite.jpg",
      price: 120,
      countInStock: 10,
      brand: "glassPro",
      rating: 3.5,
      numReviews: 10,
      description: "Produkt wysokiej jakości",
    },
    {
      _id: "2",
      name: "Mate 20 Lite",
      category: "Szkła hartowane",
      image: "images/Mate20Lite.jpg",
      price: 100,
      countInStock: 15,
      brand: "glassPro",
      rating: 4.0,
      numReviews: 10,
      description: "Produkt wysokiej jakości",
    },
    {
      _id: "3",
      name: "Mate 30 Lite",
      category: "Szkła hartowane",
      image: "images/Mate30Lite.jpg",
      price: 220,
      countInStock: 13,
      brand: "glassPro",
      rating: 4.8,
      numReviews: 17,
      description: "Produkt wysokiej jakości",
    },
    {
      _id: "4",
      name: "P10 Lite",
      category: "Szkła hartowane",
      image: "images/P10Lite.jpg",
      price: 78,
      countInStock: 9,
      brand: "glassPro",
      rating: 4.5,
      numReviews: 14,
      description: "Produkt wysokiej jakości",
    },
    {
      _id: "5",
      name: "P20 Lite",
      category: "Szkła hartowane",
      image: "images/P20Lite.jpg",
      countInStock: 0,
      price: 65,
      brand: "glassPro",
      rating: 4.5,
      numReviews: 10,
      description: "Produkt wysokiej jakości",
    },
    {
      _id: "6",
      name: "P30 Lite",
      category: "Szkła hartowane",
      image: "images/P30Lite.jpg",
      countInStock: 0,
      price: 139,
      brand: "glassPro",
      rating: 1.5,
      numReviews: 15,
      description: "Produkt wysokiej jakości",
    },
    {
      _id: "7",
      name: "P30 Pro",
      category: "Szkła hartowane",
      image: "images/P30Pro.jpg",
      countInStock: 1,
      price: 139,
      brand: "glassPro",
      rating: 5,
      numReviews: 15,
      description: "Produkt wysokiej jakości",
    },
  ],
};
export default data;
